AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura Viva - Base de datos RDS

Parameters:

  DBUsername:
    Type: String
    Default: admin

  DBPassword:
    Type: String
    NoEcho: true

Resources:

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acceso MySQL
    #   VpcId: vpc-XXXXXXXX
      VpcId: vpc-0f00bbb098b3d63a5
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subredes privadas para RDS
      SubnetIds:
        # - subnet-PRIVATE-A
        # - subnet-PRIVATE-B
        - subnet-05017fd9a836eac7d
        - subnet-013b91f25176ed4b6

  VivaDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: viva-db
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 7