AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura Viva - Base de datos NoSQL DynamoDB

Resources:

  VivaDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VivaUsers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
      Tags:
        - Key: Project
          Value: InfraestructuraViva