AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura Viva - Servidor EC2

Parameters:

  KeyName:
    Description: Nombre del KeyPair para acceder por SSH
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir SSH y HTTP
    #   VpcId: vpc-XXXXXXXX
      VpcId: vpc-0f00bbb098b3d63a5
      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  VivaServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
        #   SubnetId: subnet-XXXXXXXX
          SubnetId: subnet-080631a3983498b40
          GroupSet:
            - !Ref EC2SecurityGroup