AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura Viva - Monitoreo CloudWatch

Parameters:

  InstanceId:
    Type: String
    Description: ID de la instancia EC2 a monitorear

Resources:

  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarma si CPU supera 70%
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref InstanceId
      AlarmActions: []