AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura Viva - SNS y SQS para mensajeria

Resources:

  VivaTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: viva-notifications

  VivaQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: viva-queue

  VivaQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref VivaQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt VivaQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref VivaTopic

  VivaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref VivaTopic
      Endpoint: !GetAtt VivaQueue.Arn